services:
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "18080:8080" # 카프카 ui와 안겹치게 함
      - "7077:7077"
    volumes:
      - ../:/app
      - spark-ivy:/opt/spark/.ivy2
    networks:
      - data-pipeline-net

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ../:/app
      - spark-ivy:/opt/spark/.ivy2
    networks:
      - data-pipeline-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - data-pipeline-net
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

networks:
  data-pipeline-net:
    external: true

volumes:
  spark-ivy:
  redis-data: