services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    privileged: true
    command:
      - "--docker_only=true"
      - "--housekeeping_interval=10s"
    ports:
      - "8088:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - data-pipeline-net
    cpus: 0.25
    mem_limit: 256m
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - cadvisor
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - data-pipeline-net
    cpus: 0.25
    mem_limit: 512m
    restart: unless-stopped

networks:
  data-pipeline-net:
    external: true

volumes:
  prometheus-data: